from typing import Protocol, Any, Iterable, Optional, runtime_checkable


@runtime_checkable
class PatientRepositoryProtocol(Protocol):
    def get_by_id(self, patient_id: int) -> Any: ...
    def get_all(self) -> Iterable[Any]: ...
    def create(self, full_name: str, date_of_birth, phone_number: Optional[str] = None) -> Any: ...
    def update(self, patient_id: int, **kwargs) -> Any: ...
    def delete(self, patient_id: int) -> None: ...
    def find_by_period_and_work(self, start_date, end_date, work_category_id) -> Iterable[Any]: ...


@runtime_checkable
class AppointmentRepositoryProtocol(Protocol):
    def get_by_id(self, appointment_id: int) -> Any: ...
    def get_by_work_and_period(self, start_date, end_date, work_category_id) -> Iterable[Any]: ...
    def create_appointment(self, request_id, notes="") -> Any: ...
    def update_appointment(self, appointment_id, notes=None) -> Any: ...
    def add_work(self, appointment_id, work_category_id, price=None, cost=0, profit=0) -> Any: ...
    def add_material(self, appointment_work_id, material_category_id, quantity, cost) -> Any: ...
    def add_medicine(self, appointment_work_id, medicine_category_id, quantity, cost) -> Any: ...
    def add_procedure(self, appointment_work_id, procedure_category_id, cost) -> Any: ...


@runtime_checkable
class DictionaryRepositoryProtocol(Protocol):
    def get_all_work_categories(self) -> Iterable[Any]: ...
    def get_all_material_categories(self) -> Iterable[Any]: ...
    def get_all_medicine_categories(self) -> Iterable[Any]: ...
    def get_all_procedure_categories(self) -> Iterable[Any]: ...
    def get_all_doctors(self) -> Iterable[Any]: ...
    def create_work_category(self, name) -> Any: ...
    def create_material_category(self, name) -> Any: ...
    def create_medicine_category(self, name) -> Any: ...
    def create_procedure_category(self, name) -> Any: ...
    def create_doctor(self, full_name, specialization) -> Any: ...


@runtime_checkable
class FinancialReportRepositoryProtocol(Protocol):
    def get_work_category_financials(self) -> Iterable[Any]: ...
    def get_appointment_work_financials_by_id(self, appointment_work_id: int) -> Optional[dict]: ...


@runtime_checkable
class ProtocolRepositoryProtocol(Protocol):
    def get_patient_appointments(self, patient_id: int) -> Iterable[Any]: ...


@runtime_checkable
class RequestRepositoryProtocol(Protocol):
    def create(self, datetime, patient_id, doctor_id=None) -> Any: ...
    def get_by_id(self, request_id) -> Any: ...
    def get_all(self) -> Iterable[Any]: ...
    def update(self, request_id, **kwargs) -> Any: ...
    def delete(self, request_id) -> None: ...
