# Generated by Django 5.1.2 on 2026-05-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ Лікаря')),
                ('specialization', models.CharField(max_length=100, verbose_name='Спеціалізація')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клас матеріалу')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клас ліків')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ Пацієнта')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клас процедури')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клас роботи')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата та час заявки')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.request')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Витрати на роботу')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибуток')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='hospital.appointment')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Витрати на матеріал')),
                ('appointment_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hospital.appointmentwork')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.materialcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Витрати на ліки')),
                ('appointment_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='hospital.appointmentwork')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.medicinecategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Витрати на процедуру')),
                ('appointment_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='hospital.appointmentwork')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.procedurecategory')),
            ],
        ),
    ]
