# Generated by Django 5.1.2 on 2026-05-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Прийом', 'verbose_name_plural': 'Прийоми'},
        ),
        migrations.AlterModelOptions(
            name='appointmentwork',
            options={'verbose_name': 'Робота в прийомі', 'verbose_name_plural': 'Роботи в прийомі'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Лікар', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'Клас матеріалу', 'verbose_name_plural': 'Класи матеріалів'},
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'verbose_name': 'Клас ліків', 'verbose_name_plural': 'Класи ліків'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пацієнт', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterModelOptions(
            name='procedurecategory',
            options={'verbose_name': 'Клас процедури', 'verbose_name_plural': 'Класи процедур'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'verbose_name': 'Клас роботи', 'verbose_name_plural': 'Класи робіт'},
        ),
        migrations.AlterModelOptions(
            name='workmaterial',
            options={'verbose_name': 'Матеріал у роботі', 'verbose_name_plural': 'Матеріали у роботі'},
        ),
        migrations.AlterModelOptions(
            name='workmedicine',
            options={'verbose_name': 'Ліки у роботі', 'verbose_name_plural': 'Ліки у роботі'},
        ),
        migrations.AlterModelOptions(
            name='workprocedure',
            options={'verbose_name': 'Процедура у роботі', 'verbose_name_plural': 'Процедури у роботі'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='appointmentwork',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='hospital.appointment', verbose_name='Прийом'),
        ),
        migrations.AlterField(
            model_name='appointmentwork',
            name='work_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.workcategory', verbose_name='Категорія роботи'),
        ),
        migrations.AlterField(
            model_name='request',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='request',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient', verbose_name='Пацієнт'),
        ),
        migrations.AlterField(
            model_name='workmaterial',
            name='appointment_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hospital.appointmentwork', verbose_name='Робота в прийомі'),
        ),
        migrations.AlterField(
            model_name='workmaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.materialcategory', verbose_name='Категорія матеріалу'),
        ),
        migrations.AlterField(
            model_name='workmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='workmedicine',
            name='appointment_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='hospital.appointmentwork', verbose_name='Робота в прийомі'),
        ),
        migrations.AlterField(
            model_name='workmedicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.medicinecategory', verbose_name='Категорія ліків'),
        ),
        migrations.AlterField(
            model_name='workmedicine',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='workprocedure',
            name='appointment_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='hospital.appointmentwork', verbose_name='Робота в прийомі'),
        ),
        migrations.AlterField(
            model_name='workprocedure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.procedurecategory', verbose_name='Категорія процедури'),
        ),
    ]
