# Generated by Django 5.1.2 on 2026-05-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentwork',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='appointmentwork',
            name='profit',
        ),
        migrations.AddField(
            model_name='appointmentwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна роботи'),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('work_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.workcategory', verbose_name='Клас роботи')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листи',
            },
        ),
    ]
