# Generated by Django 5.1.2 on 2026-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_appointmentwork_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базова вартість (закупівля)'),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базова вартість (закупівля)'),
        ),
        migrations.AddField(
            model_name='procedurecategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базова вартість (витрати)'),
        ),
    ]
