# Generated by Django 5.1.2 on 2026-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_materialcategory_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Вартість роботи'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Базова вартість (закупівля)'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Базова вартість (закупівля)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='procedurecategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Базова вартість (витрати)'),
        ),
    ]
