# Generated by Django 5.1.2 on 2026-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_workcategory_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentwork',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальні витрати'),
        ),
        migrations.AddField(
            model_name='appointmentwork',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прибуток'),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='patient_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна для пацієнта (дохід клініки)'),
        ),
        migrations.AlterField(
            model_name='appointmentwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна роботи (фіксація доходу)'),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Власна собівартість роботи (витрати клініки)'),
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
