# Generated by Django 5.1.2 on 2026-05-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_appointmentwork_cost_appointmentwork_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workcategory',
            old_name='cost_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='patient_price',
        ),
    ]
