# Generated by Django 5.1.2 on 2026-05-23 20:27

import django.core.validators
import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_rename_cost_price_workcategory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[hospital.models.validate_birth_date], verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[^0-9]+$', message='У полі ПІБ не можна вводити цифри.')], verbose_name='ПІБ Пацієнта'),
        ),
    ]
