# Generated by Django 6.0.5 on 2026-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_patient_phone_number_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='appointmentwork',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='patient',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='request',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='workmaterial',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='workmedicine',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='workprocedure',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
    ]
